language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_wait composer update --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit

notifications:
  email: false
